{$ifdef VER80}
{$define DELPHI1}
{$define DELPHI1_UP}
{$endif}

{$ifdef VER90}
{$define DELPHI2}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$endif}

{$ifdef VER100}
{$define DELPHI3}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$endif}

{$ifdef VER120}
{$define DELPHI4}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$endif}

{$ifdef VER130}
{$define DELPHI5}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$endif}

{$ifdef VER140}
{$define DELPHI6}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$endif}

{$ifdef VER150}
{$define DELPHI7}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$endif}

{$ifdef VER160}
{$define DELPHI8}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$endif}

{$ifdef VER170}
{$define DELPHI2005}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$endif}

{$ifdef VER180}
{$define DELPHI2006}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$endif}

{$ifdef VER185}
{$define DELPHI2007}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$define DELPHI2007_UP}
{$endif}

{$ifdef VER200}
{$define DELPHI2009}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$define DELPHI2007_UP}
{$define DELPHI2009_UP}
{$endif}

{$ifdef VER210}
{$define DELPHI2010}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$define DELPHI2007_UP}
{$define DELPHI2009_UP}
{$define DELPHI2010_UP}
{$endif}

{$ifdef VER220}
{$define DELPHI_XE}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$define DELPHI2007_UP}
{$define DELPHI2009_UP}
{$define DELPHI2010_UP}
{$define DELPHI_XE_UP}
{$endif}

{$ifdef VER230}
{$define DELPHI_XE2}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$define DELPHI2007_UP}
{$define DELPHI2009_UP}
{$define DELPHI2010_UP}
{$define DELPHI_XE_UP}
{$define DELPHI_XE2_UP}
{$endif}

{$ifdef VER240}
{$define DELPHI_XE3}
{$define DELPHI1_UP}
{$define DELPHI2_UP}
{$define DELPHI3_UP}
{$define DELPHI4_UP}
{$define DELPHI5_UP}
{$define DELPHI6_UP}
{$define DELPHI7_UP}
{$define DELPHI8_UP}
{$define DELPHI2005_UP}
{$define DELPHI2006_UP}
{$define DELPHI2007_UP}
{$define DELPHI2009_UP}
{$define DELPHI2010_UP}
{$define DELPHI_XE_UP}
{$define DELPHI_XE2_UP}
{$define DELPHI_XE3_UP}
{$endif}

// VER 270 (Embarcadero RAD Studio XE6)
{$IFDEF VER270}
  {$DEFINE DXE6_OR_HIGHER}
{$ENDIF}
{$IFDEF VER280}
  {$DEFINE DXE6_OR_HIGHER}
{$ENDIF}
{$IFDEF VER290}
  {$DEFINE DXE6_OR_HIGHER}
{$ENDIF}
{$IFDEF VER300}
  {$DEFINE DXE6_OR_HIGHER}
{$ENDIF}

{$IFDEF DXE6_OR_HIGHER}
  {$UNDEF VER_UNKNOWN}
  {$DEFINE VER22x}
  {$DEFINE VCL150}

  {$IFDEF MSWINDOWS}
  {$IFDEF BCB}
  {$DEFINE BCB5_OR_HIGHER}
  {$DEFINE BCB6_OR_HIGHER}
  {$OBJEXPORTALL ON}
  {$ELSE}
  {$DEFINE DELPHI}
  {$DEFINE DELPHI14}
  {$DEFINE DELPHIXE}
  {$DEFINE DELPHIXE6}
  {$DEFINE D5_OR_HIGHER}
  {$DEFINE D6_OR_HIGHER}
  {$DEFINE D7_OR_HIGHER}
  {$DEFINE D8_OR_HIGHER}
  {$DEFINE D9_OR_HIGHER}
  {$DEFINE D10_OR_HIGHER}
  {$DEFINE D2007_OR_HIGHER}
  {$DEFINE D12_OR_HIGHER}
  {$DEFINE D2009_OR_HIGHER}
  {$DEFINE D13_OR_HIGHER}
  {$DEFINE D2010_OR_HIGHER}
  {$DEFINE D14_OR_HIGHER}
  {$DEFINE DXE_OR_HIGHER}
  {$ENDIF}
  {.$DEFINE DOT_NET_WARNINGS_OFF}
  {$ELSE}
      // Non-Windows compiler (i.e. Kylix)
  {$ENDIF}


  {$DEFINE VCL40_OR_HIGHER}
  {$DEFINE VCL50_OR_HIGHER}
  {$DEFINE VCL60_OR_HIGHER}
  {$DEFINE VCL70_OR_HIGHER}
  {$DEFINE VCL90_OR_HIGHER}
  {$DEFINE VCL100_OR_HIGHER}
  {$DEFINE VCL110_OR_HIGHER}
  {$DEFINE VCL140_OR_HIGHER}
  {$DEFINE VCL150_OR_HIGHER}

  {$define DELPHI_XE6}
  {$define DELPHI1_UP}
  {$define DELPHI2_UP}
  {$define DELPHI3_UP}
  {$define DELPHI4_UP}
  {$define DELPHI5_UP}
  {$define DELPHI6_UP}
  {$define DELPHI7_UP}
  {$define DELPHI8_UP}
  {$define DELPHI2005_UP}
  {$define DELPHI2006_UP}
  {$define DELPHI2007_UP}
  {$define DELPHI2009_UP}
  {$define DELPHI2010_UP}
  {$define DELPHI_XE_UP}
  {$define DELPHI_XE2_UP}
  {$define DELPHI_XE3_UP}
  {$define DELPHI_XE4_UP}
  {$define DELPHI_XE5_UP}
{$ENDIF}
